package co.edu.unab;

import co.edu.unab.ppa.FrmCalcularKNet;
import co.edu.unab.ppa.FrmCalcularNetKDE;
import co.edu.unab.ppa.FrmCargarRedes;
import co.edu.unab.ppa.FrmCargarEventos;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * @author Feisar Moreno
 * @date 24/02/2016
 */
public class FrmPrincipal extends JFrame {
    public FrmPrincipal() {
        initComponents();
        
        this.setExtendedState(FrmPrincipal.MAXIMIZED_BOTH);
    }
    
    public JPanel getPanPrincipal() {
        return this.panPrincipal;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrincipal = new javax.swing.JPanel();
        mbrPrincipal = new javax.swing.JMenuBar();
        jMenuConfiguracion = new javax.swing.JMenu();
        mitBaseDatos = new javax.swing.JMenuItem();
        jMenuCarga = new javax.swing.JMenu();
        mitCargaRed = new javax.swing.JMenuItem();
        mitCargaPuntos = new javax.swing.JMenuItem();
        jMenuProcesos = new javax.swing.JMenu();
        mitKNET = new javax.swing.JMenuItem();
        mitNetKDE = new javax.swing.JMenuItem();
        menAyuda = new javax.swing.JMenu();
        mitAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Point Pattern Analysis on Network Spaces");

        panPrincipal.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        mbrPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuConfiguracion.setText("Configuration");

        mitBaseDatos.setText("Database");
        mitBaseDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitBaseDatosActionPerformed(evt);
            }
        });
        jMenuConfiguracion.add(mitBaseDatos);

        mbrPrincipal.add(jMenuConfiguracion);

        jMenuCarga.setText("Upload");

        mitCargaRed.setText("Upload network files");
        mitCargaRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitCargaRedActionPerformed(evt);
            }
        });
        jMenuCarga.add(mitCargaRed);

        mitCargaPuntos.setText("Upload event (points) files");
        mitCargaPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitCargaPuntosActionPerformed(evt);
            }
        });
        jMenuCarga.add(mitCargaPuntos);

        mbrPrincipal.add(jMenuCarga);

        jMenuProcesos.setText("Processes");

        mitKNET.setText("Network K function");
        mitKNET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitKNETActionPerformed(evt);
            }
        });
        jMenuProcesos.add(mitKNET);

        mitNetKDE.setText("NetKDE");
        mitNetKDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNetKDEActionPerformed(evt);
            }
        });
        jMenuProcesos.add(mitNetKDE);

        mbrPrincipal.add(jMenuProcesos);

        menAyuda.setText("Help");

        mitAcercaDe.setText("About");
        mitAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAcercaDeActionPerformed(evt);
            }
        });
        menAyuda.add(mitAcercaDe);

        mbrPrincipal.add(menAyuda);

        setJMenuBar(mbrPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void mitCargaRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitCargaRedActionPerformed
        this.abrirItemMenu(ItemsMenuPpal.CARGAR_REDES);
    }//GEN-LAST:event_mitCargaRedActionPerformed
    
    private void mitCargaPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitCargaPuntosActionPerformed
        this.abrirItemMenu(ItemsMenuPpal.CARGAR_EVENTOS);
    }//GEN-LAST:event_mitCargaPuntosActionPerformed

    private void mitAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAcercaDeActionPerformed
        this.abrirItemMenu(ItemsMenuPpal.ACERCA_DE);
    }//GEN-LAST:event_mitAcercaDeActionPerformed

    private void mitKNETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitKNETActionPerformed
        this.abrirItemMenu(ItemsMenuPpal.CALCULAR_KNET);
    }//GEN-LAST:event_mitKNETActionPerformed

    private void mitNetKDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNetKDEActionPerformed
        this.abrirItemMenu(ItemsMenuPpal.CALCULAR_NETKDE);
    }//GEN-LAST:event_mitNetKDEActionPerformed

    private void mitBaseDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitBaseDatosActionPerformed
        this.abrirItemMenu(ItemsMenuPpal.BASE_DATOS);
    }//GEN-LAST:event_mitBaseDatosActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
        }

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    
    public void abrirItemMenu(ItemsMenuPpal itemMenuPpal) {
        Component comps[] = this.panPrincipal.getComponents();
        int i = 0;
        while(comps != null && i < comps.length) {
            this.panPrincipal.remove(comps[i]);
            i++;
        }
        this.panPrincipal.revalidate();
        this.panPrincipal.repaint();
        
        switch (itemMenuPpal) {
            case BASE_DATOS:
                FrmBaseDatos frmBaseDatos = new FrmBaseDatos(this);
                this.panPrincipal.add(frmBaseDatos);
                frmBaseDatos.setVisible(true);
                break;
            case CARGAR_REDES:
                FrmCargarRedes frmCargaRedes = new FrmCargarRedes(this);
                this.panPrincipal.add(frmCargaRedes);
                frmCargaRedes.setVisible(true);
                break;
            case CARGAR_EVENTOS:
                FrmCargarEventos frmCargarEventos = new FrmCargarEventos(this);
                this.panPrincipal.add(frmCargarEventos);
                frmCargarEventos.setVisible(true);
                break;
            case CALCULAR_KNET:
                FrmCalcularKNet frmCalcularKNet = new FrmCalcularKNet(this);
                this.panPrincipal.add(frmCalcularKNet);
                frmCalcularKNet.setVisible(true);
                break;
            case CALCULAR_NETKDE:
                FrmCalcularNetKDE frmCalcularNetKDE = new FrmCalcularNetKDE(this);
                this.panPrincipal.add(frmCalcularNetKDE);
                frmCalcularNetKDE.setVisible(true);
                break;
            case ACERCA_DE:
                FrmAcercaDe frmAcercaDe = new FrmAcercaDe();
                this.panPrincipal.add(frmAcercaDe);
                frmAcercaDe.setVisible(true);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Option value unknown", "Main Menu", JOptionPane.ERROR_MESSAGE);
                break;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuCarga;
    private javax.swing.JMenu jMenuConfiguracion;
    private javax.swing.JMenu jMenuProcesos;
    private javax.swing.JMenuBar mbrPrincipal;
    private javax.swing.JMenu menAyuda;
    private javax.swing.JMenuItem mitAcercaDe;
    private javax.swing.JMenuItem mitBaseDatos;
    private javax.swing.JMenuItem mitCargaPuntos;
    private javax.swing.JMenuItem mitCargaRed;
    private javax.swing.JMenuItem mitKNET;
    private javax.swing.JMenuItem mitNetKDE;
    private javax.swing.JPanel panPrincipal;
    // End of variables declaration//GEN-END:variables
}
